version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      - postgresql
      - adminer

  postgresql:
    image: postgres
    container_name: postgresql
    restart: no
    environment:
      POSTGRES_USER: anpoliakov
      POSTGRES_PASSWORD: anpoliakov
      POSTGRES_DB: wallet_service
#      PGDATA: /var/lib/postgresql/data
#    volumes:
#      - ./db/shortcut/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: no
    ports:
      - 8080:8080